# Generated by Django 4.2.1 on 2023-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_book_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="total_time",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="total_time",
            field=models.FloatField(default=0),
        ),
    ]
